repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.2.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg
        args: ["build", "bump", "chore", "ci", "docs","feat", "fix", "perf", "refactor", "revert", "style", "test"]
